run:
  skip-dirs:
    - testing
  allow-parallel-runners: true
  timeout: 5m
linters:
  enable-all: true
  disable:
    - wsl
    - maligned
    - gochecknoglobals
    - nolintlint
    - wrapcheck # Should be deleted
    - varnamelen
    - goerr113
    - godox
    - paralleltest
    - nonamedreturns
    - musttag # Should be deleted
    - ireturn
    - exhaustivestruct
    - forcetypeassert # Should be deleted
    - exhaustruct
    - ifshort
    - gci
    - funlen # Should be deleted
    - maintidx
    - containedctx
    - gofmt
    - scopelint # Should be deleted
    # deplicated
    - golint
    - deadcode
    - interfacer
    - nosnakecase
    - structcheck
    - varcheck
linters-settings:
  lll:
    line-length: 140
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - log
    packages-with-error-message:
      - log: "logging is allowed only by fisherman/pkg/log"
      - gopkg.in/yaml.v2: "please use v3"
      - gopkg.in/yaml.v1: "please use v3"
  tagliatelle:
    case:
      rules:
        yaml: kebab
  gosec:
    excludes:
      - G204
presets:
  - bugs
  - comment
  - complexity
  - error
  - format
  - import
  - metalinter
  - module
  - performance
  - style
  - test
  - unused
