builds:
  - goos:
      - linux
      - windows
      - darwin
    flags:
      - -tags=release
      - -v
    ldflags:
      - -s -w -X fisherman/constants.Version={{.Version}}

archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: 32-bit
      amd64: 64-bit
    files:
      - LICENSE

source:
  enabled: false

changelog:
  skip: true
