// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileWriter is an autogenerated mock type for the FileWriter type
type FileWriter struct {
	mock.Mock
}

// Write provides a mock function with given fields: path, content
func (_m *FileWriter) Write(path string, content string) error {
	ret := _m.Called(path, content)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(path, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
