FROM rust:slim

RUN rustup target add x86_64-pc-windows-gnu

RUN apt-get update
RUN apt-get install -y --no-install-recommends pkg-config mingw-w64

RUN rm -rf /var/lib/apt/lists/*

ENV PKG_CONFIG_ALLOW_CROSS=1
ENV PKG_CONFIG_PATH=/usr/x86_64-w64-mingw32/lib/pkgconfig
ENV PKG_CONFIG_SYSROOT_DIR=/usr/x86_64-w64-mingw32
