FROM rust:latest

RUN dpkg --add-architecture arm64
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        git \
        pkg-config \
        gcc-aarch64-linux-gnu \
        g++-aarch64-linux-gnu \
        libssl-dev:arm64 \
        musl-tools \
        cmake \
        libssh2-1-dev:arm64 \
        zlib1g-dev:arm64

RUN rm -rf /var/lib/apt/lists/*

ENV PKG_CONFIG_ALLOW_CROSS=1
ENV OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu
ENV OPENSSL_INCLUDE_DIR=/usr/include
ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
ENV RUSTFLAGS="-C linker=aarch64-linux-gnu-gcc"

RUN rustup target add aarch64-unknown-linux-gnu