// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Shell is an autogenerated mock type for the Shell type
type Shell struct {
	mock.Mock
}

// Exec provides a mock function with given fields: commands, env, output
func (_m *Shell) Exec(commands []string, env *map[string]string, output bool) (string, int, error) {
	ret := _m.Called(commands, env, output)

	var r0 string
	if rf, ok := ret.Get(0).(func([]string, *map[string]string, bool) string); ok {
		r0 = rf(commands, env, output)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func([]string, *map[string]string, bool) int); ok {
		r1 = rf(commands, env, output)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func([]string, *map[string]string, bool) error); ok {
		r2 = rf(commands, env, output)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
