// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	shell "fisherman/infrastructure/shell"
)

// Shell is an autogenerated mock type for the Shell type
type Shell struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, script
func (_m *Shell) Exec(ctx context.Context, script shell.ScriptConfig) shell.ExecResult {
	ret := _m.Called(ctx, script)

	var r0 shell.ExecResult
	if rf, ok := ret.Get(0).(func(context.Context, shell.ScriptConfig) shell.ExecResult); ok {
		r0 = rf(ctx, script)
	} else {
		r0 = ret.Get(0).(shell.ExecResult)
	}

	return r0
}
