name: Markdown

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: '*'

jobs:
  lint-docs:
    name: Check Markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint markdown documentation
        uses: ruzickap/action-my-markdown-linter@v1
